config/routes.rb
Rails.application.routes.draw do
  get 'receiptors/new'
  get 'receiptors/create'

  devise_for :users

  root to: "pages#home"
  get 'settings', to: 'settings#index'
  put 'settings', to: 'settings#update'

  resources :choices, only: %i[index show create new edit] do
    resources :receiptors
    resources :options do
      resources :option_choices, only: :create
    end
  end


end

# Path: app/controllers/settings_controller.rb

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :user
  has_many :option_choices
  has_many :options, through: :option_choices
  has_many :receiptors
end

app/models/option.rb
class Option < ApplicationRecord
  has_one_attached :photo
  has_many :option_choices
  has_many :choices, through: :option_choices
end

app/models/option_choice.rb
class OptionChoice < ApplicationRecord
  belongs_to :option
  belongs_to :choice
end

app/models/receiptor.rb
class Receiptor < ApplicationRecord
  belongs_to :user
  belongs_to :choice

  validates :name, presence: true
  validates :email, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  # validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }

  has_many :choices, dependent: :destroy
  has_many :receiptors
  has_one_attached :photo

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/choices_controller.rb
class ChoicesController < ApplicationController
  before_action :set_choice, only: %i[show destroy]

  def index
    @choices = Choice.all
    @options = Option.all
  end

  def show
    @endgame = OptionChoice.where(choice_id: params[:id])
    @options = Option.all
    @counter = @endgame.length

    loop do
      @i = @options.ids.sample
      @k = @options.ids.sample
      if (@choice.options.pluck(:id).include?(@i) == false) && (@choice.options.pluck(:id).include?(@k) == false) && @i != @k
        @optioni = @options.find(@i)
        @optionk = @options.find(@k)
        break
      end
    end
  end

  def edit
    @endgame = OptionChoice.where(choice_id: params[:id])
    @choice = Choice.find(params[:id])
    @options_our = @choice.options.ids
    @options = Option.all
    @counter = @endgame.length

    loop do
      @i = @options.ids.sample
      @k =  @options_our.sample
      if @options_our.count(@k) == 1 && @i != @k && @options_our.count(@i) == 0
        @optionk = @options.find(@k)
        @optioni = @options.find(@i)
      break
      end



     end

  end

  def new
    @choice = Choice.new
  end

  def create
    @choice = Choice.new
    @choice.user = current_user
    @choice.save
    redirect_to choice_path(@choice)
  end

  def update
    @choice.update(choice_params)
  end

  def destroy
    @choice.destroy
    # redirect_to player_bookings_path(@choice), status: :see_other
  end

  # def mychoices
  #   @choices = policy_scope(Choice)
  #   @mychoices = current_user.choices

  # end

  private

  def set_choice
    @choice = Choice.find(params[:id])
  end
end

app/controllers/option_choices_controller.rb
class OptionChoicesController < ApplicationController

  def create
    @endgame = OptionChoice.where(choice_id: params[:choice_id])
    if @endgame.length < 4
      @optionchoice = OptionChoice.new(choice_id: params[:choice_id], option_id: params[:option_id])
      @optionchoice.save
      redirect_to choice_path(params[:choice_id])
    end

      if @endgame.length == 4

        @optionchoice = OptionChoice.new(choice_id: params[:choice_id], option_id: params[:option_id])
        @optionchoice.save
        redirect_to "/choices/#{params[:choice_id]}/receiptors/new"
        return

      end

      if  @endgame.length > 4 && @endgame.length <9
      @optionchoice = OptionChoice.new(choice_id: params[:choice_id], option_id: params[:option_id])
      @optionchoice.save
      redirect_to "/choices/#{params[:choice_id]}/edit"
      end

      if @endgame.length == 9

        @optionchoice = OptionChoice.new(choice_id: params[:choice_id], option_id: params[:option_id])
        @optionchoice.save
        redirect_to "/choices"
        return
      end


  end

end

app/controllers/options_controller.rb
class OptionsController < ApplicationController
  def show
    @choice = Choice.new
    @options = Option.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/receiptors_controller.rb
class ReceiptorsController < ApplicationController
  def new
    @choice = Choice.find(params[:choice_id])
  end

  def create
    user = User.find_by(email: params[:receiptor][:email])
    if user.nil?
      user = User.create(email: params[:receiptor][:email], password: 123456, name: params[:receiptor][:name])
    end
    receiptor = Receiptor.new(user_id: user.id, choice_id: params[:choice_id], name: params[:receiptor][:name], email: params[:receiptor][:email])
    receiptor.save

    redirect_to "/"


  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  def index
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      flash[:success] = "Your settings have been updated."
      redirect_to root_path
    else
      render "index"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/choices/edit.html.erb
<%= render "shared/navbar" %>

<div class=landing-page>
    <div class="news">

     <h2 class="header-newr text-center">Select your options</h2>
      <div class="container container-show-white">

          <div class="container container-show">

              <% option1 = @options[1]%>
              <% option2 = @options[2]%>
              <% option3 = @options[3]%>
              <% option4 = @options[4]%>
              <% option5 = @options[5]%>
              <% option6 = @options[6]%>

              <div class="row" style="justify-content: center;">

                  <div class="col-6">
                      <div class="cube-container">
                        <%= link_to choice_option_option_choices_path(@choice, @optioni), data: {turbo_method: :post } do%>
                          <div class = "cube left-cube">

                            <%= cl_image_tag option2.photo.key %>
                            <%= cl_image_tag option3.photo.key %>

                            <%= cl_image_tag @optioni.photo.key, data: {
                            add_in_choices_target: "event",
                            action: "click->add-in-choices#add",
                            id: @optioni.id,
                            }
                            %>


                            <%= cl_image_tag option1.photo.key %>

                          </div>
                        <% end %>

                      </div>

                  </div>



                  <div class="col-6">

                    <div class="cube-container">

                        <%= link_to choice_option_option_choices_path(@choice, @optionk), data: {turbo_method: :post } do%>

                          <div class = "cube right-cube">
                            <%= cl_image_tag option4.photo.key,  :crop=>"fill" %>
                            <%= cl_image_tag option5.photo.key,  :crop=>"fill" %>

                            <%= cl_image_tag @optionk.photo.key,  :crop=>"fill", data: {
                            add_in_choices_target: "event",
                            action: "click->add-in-choices#add",
                            id: @optionk.id

                            }
                            %>

                            <%= cl_image_tag option6.photo.key,  :crop=>"fill" %>
                          </div>
                        <% end %>
                      </div>

                  </div>

              </div>

          </div>

      </div>
    </div>
        <div class="container-new">
                <div class="parent-div">
                    <div class="img-container">
                      <div id="img1">
                        <%= @optioni.name %>
                      </div>
                    </div>
                    <div class="line-break-container">
                      <div id="line-break"></div>
                    </div>
                    <div class="img-container">
                      <div id="img2">
                        <%= @optionk.name %>
                      </div>
                    </div>
                </div>
        </div>

        <div class="counter">
            <% case @counter %>
            <% when 0 %>
            <div class="d-flex">
            <i class="fa-solid fa-circle"></i>
            <i class="fa-regular fa-circle"></i>
            <i class="fa-regular fa-circle"></i>
            <i class="fa-regular fa-circle"></i>
            <i class="fa-regular fa-circle"></i>
            </div>
            <% when 1 %>
            <div class="d-flex">
            <i class="fa-solid fa-circle"></i>
            <i class="fa-solid fa-circle"></i>
            <i class="fa-regular fa-circle"></i>
            <i class="fa-regular fa-circle"></i>
            <i class="fa-regular fa-circle"></i>
            </div>
            <% when 2 %>
            <div class="d-flex">
            <i class="fa-solid fa-circle"></i>
            <i class="fa-solid fa-circle"></i>
            <i class="fa-solid fa-circle"></i>
            <i class="fa-regular fa-circle"></i>
            <i class="fa-regular fa-circle"></i>
            </div>
            <% when 3 %>
            <div class="d-flex">
            <i class="fa-solid fa-circle"></i>
            <i class="fa-solid fa-circle"></i>
            <i class="fa-solid fa-circle"></i>
            <i class="fa-solid fa-circle"></i>
            <i class="fa-regular fa-circle"></i>
            </div>
            <% when 4 %>
            <div class="d-flex">
            <i class="fa-solid fa-circle"></i>
            <i class="fa-solid fa-circle"></i>
            <i class="fa-solid fa-circle"></i>
            <i class="fa-solid fa-circle"></i>
            <i class="fa-solid fa-circle"></i>
            </div>
            <% when 5 %>
            <div class="d-flex">
            <i class="fa-solid fa-circle"></i>
            <i class="fa-regular fa-circle"></i>
            <i class="fa-regular fa-circle"></i>
            <i class="fa-regular fa-circle"></i>
            <i class="fa-regular fa-circle"></i>
            </div>
            <% when 6 %>
            <div class="d-flex">
            <i class="fa-solid fa-circle"></i>
            <i class="fa-solid fa-circle"></i>
            <i class="fa-regular fa-circle"></i>
            <i class="fa-regular fa-circle"></i>
            <i class="fa-regular fa-circle"></i>
            </div>
            <% when 7 %>
             <div class="d-flex">
            <i class="fa-solid fa-circle"></i>
            <i class="fa-solid fa-circle"></i>
            <i class="fa-solid fa-circle"></i>
            <i class="fa-regular fa-circle"></i>
            <i class="fa-regular fa-circle"></i>
            </div>
            <% when 8 %>
             <div class="d-flex">
            <i class="fa-solid fa-circle"></i>
            <i class="fa-solid fa-circle"></i>
            <i class="fa-solid fa-circle"></i>
            <i class="fa-solid fa-circle"></i>
            <i class="fa-regular fa-circle"></i>
            </div>
            <% when 9 %>
             <div class="d-flex">
            <i class="fa-solid fa-circle"></i>
            <i class="fa-solid fa-circle"></i>
            <i class="fa-solid fa-circle"></i>
            <i class="fa-solid fa-circle"></i>
            <i class="fa-solid fa-circle"></i>
            </div>

            <% end %>

        </div>
</div>










<style>
@import url('https://fonts.googleapis.com/css2?family=Changa+One&display=swap');
@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300&display=swap');

@keyframes reveal-left-to-right {
  from {
    opacity: 0;

    transform: translateX(110%);
  }
  to {
    opacity: 1;
    transform: translateX(0px);
  }
}

@keyframes reveal-right-to-left {
  from {
    opacity: 0;
    transform: translateX(-110%);
  }
  to {
    opacity: 1;
    transform: translateX(0px);
  }
}
@keyframes counter-reveal {
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
}

@keyframes grow-line {
  from {

    opacity: 0;
    height: 0;
  }
  to {
    opacity: 1;
    height: 100%;
  }
}
.counter {
  position: relative;
  top: -290px;
  color: #ed6d76;
  opacity: 0;
  animation: counter-reveal ease-out 1s forwards;
  animation-delay: 2.5s;
}

.container-new {
  position: relative;
  top: -600px;
  right: 138px;
  background-color: transparent;
  /* min-height: 100vh; */
  display: flex;
  justify-content: center;
  align-items: center;
}

#container-show {
  position: absolute;
}

.parent-div {

  background-color: transparent;
  height: 200px;
  width: 50%;
  display: flex;
  justify-content: space-between;
}

 /* .line-break-container {

  display: flex;
  align-items: center;
}

 #line-break {
  width: 2px;

  background-color: #ff6472;
  z-index: 3;
  animation: grow-line linear 1s forwards;
  animation-delay: 1s;
}  */

.img-container {
  height: 100%;
  overflow: hidden;
  flex: 1 0 auto;
  display: flex;
  justify-content: center;
  align-items: center;
}

#img1, #img2 {
  color: white;
  background-color: rgba(249, 156, 166, 0.954);
  font-size: 1.5rem;
  overflow: hidden;
  width: 300px;
  height: 70px;
  font-family: 'Poppins', sans-serif;
  display: flex;
  justify-content: center;
  align-items: center;
  border-radius: 5px;
}

#img1 {
  transform: translateX(110%);
  animation: reveal-left-to-right ease-out 1s forwards;
  animation-delay: 2.5s;
}

#img2 {
  transform: translateX(-110%);
  animation: reveal-right-to-left ease-out 1s forwards;
  animation-delay: 2.5s;
}


</style>

<script>
// document.addEventListener("DOMContentLoaded", () => {
//   setTimeout(() => {
//     const img1 = document.querySelector("#img1");
//     const img2 = document.querySelector("#img2");
//     img1.className += "apply-animation";
//     img2.className += "apply-animation";
//   }, 1300);
// });
</script>

app/views/choices/new.html.erb
<%#
    <h1>Thank you for the game. Please enter your partner's email: </h1>
    <p>
      <%= simple_form_for [Receiptor.new, @choice] do |f| %>

      <%# <%= f.input :email %>
      <%# <%= f.button :submit %>
      <%# <% end %>
    <%# </p> %>

app/views/choices/show.html.erb
<%= render "shared/navbar" %>

<div class=landing-page>
    <div class="news">

     <h2 class="header-newr text-center">Select your options</h2>
      <div class="container container-show-white">

          <div class="container container-show">

              <% option1 = @options[1]%>
              <% option2 = @options[2]%>
              <% option3 = @options[3]%>
              <% option4 = @options[4]%>
              <% option5 = @options[5]%>
              <% option6 = @options[6]%>

              <div class="row" style="justify-content: center;">

                  <div class="col-6">
                      <div class="cube-container">
                        <%= link_to choice_option_option_choices_path(@choice, @optioni), data: {turbo_method: :post } do%>
                          <div class = "cube left-cube">

                            <%= cl_image_tag option2.photo.key %>
                            <%= cl_image_tag option3.photo.key %>

                            <%= cl_image_tag @optioni.photo.key, data: {
                            add_in_choices_target: "event",
                            action: "click->add-in-choices#add",
                            id: @optioni.id,
                            }
                            %>


                            <%= cl_image_tag option1.photo.key %>

                          </div>
                        <% end %>

                      </div>

                  </div>



                  <div class="col-6">

                    <div class="cube-container">

                        <%= link_to choice_option_option_choices_path(@choice, @optionk), data: {turbo_method: :post } do%>

                          <div class = "cube right-cube">
                            <%= cl_image_tag option4.photo.key,  :crop=>"fill" %>
                            <%= cl_image_tag option5.photo.key,  :crop=>"fill" %>

                            <%= cl_image_tag @optionk.photo.key,  :crop=>"fill", data: {
                            add_in_choices_target: "event",
                            action: "click->add-in-choices#add",
                            id: @optionk.id

                            }
                            %>

                            <%= cl_image_tag option6.photo.key,  :crop=>"fill" %>
                          </div>
                        <% end %>
                      </div>

                  </div>

              </div>

          </div>

      </div>
    </div>
        <div class="container-new">
                <div class="parent-div">
                    <div class="img-container">
                      <div id="img1">
                        <%= @optioni.name %>
                      </div>
                    </div>
                    <div class="line-break-container">
                      <div id="line-break"></div>
                    </div>
                    <div class="img-container">
                      <div id="img2">
                        <%= @optionk.name %>
                      </div>
                    </div>
                </div>
        </div>

        <div class="counter">
            <% case @counter %>
            <% when 0 %>
            <div class="d-flex">
            <i class="fa-solid fa-circle"></i>
            <i class="fa-regular fa-circle"></i>
            <i class="fa-regular fa-circle"></i>
            <i class="fa-regular fa-circle"></i>
            <i class="fa-regular fa-circle"></i>
            </div>
            <% when 1 %>
            <div class="d-flex">
            <i class="fa-solid fa-circle"></i>
            <i class="fa-solid fa-circle"></i>
            <i class="fa-regular fa-circle"></i>
            <i class="fa-regular fa-circle"></i>
            <i class="fa-regular fa-circle"></i>
            </div>
            <% when 2 %>
            <div class="d-flex">
            <i class="fa-solid fa-circle"></i>
            <i class="fa-solid fa-circle"></i>
            <i class="fa-solid fa-circle"></i>
            <i class="fa-regular fa-circle"></i>
            <i class="fa-regular fa-circle"></i>
            </div>
            <% when 3 %>
            <div class="d-flex">
            <i class="fa-solid fa-circle"></i>
            <i class="fa-solid fa-circle"></i>
            <i class="fa-solid fa-circle"></i>
            <i class="fa-solid fa-circle"></i>
            <i class="fa-regular fa-circle"></i>
            </div>
            <% when 4 %>
            <div class="d-flex">
            <i class="fa-solid fa-circle"></i>
            <i class="fa-solid fa-circle"></i>
            <i class="fa-solid fa-circle"></i>
            <i class="fa-solid fa-circle"></i>
            <i class="fa-solid fa-circle"></i>
            </div>
            <% when 5 %>
            <div class="d-flex">
            <i class="fa-solid fa-circle"></i>
            <i class="fa-regular fa-circle"></i>
            <i class="fa-regular fa-circle"></i>
            <i class="fa-regular fa-circle"></i>
            <i class="fa-regular fa-circle"></i>
            </div>
            <% when 6 %>
            <div class="d-flex">
            <i class="fa-solid fa-circle"></i>
            <i class="fa-solid fa-circle"></i>
            <i class="fa-regular fa-circle"></i>
            <i class="fa-regular fa-circle"></i>
            <i class="fa-regular fa-circle"></i>
            </div>
            <% when 7 %>
             <div class="d-flex">
            <i class="fa-solid fa-circle"></i>
            <i class="fa-solid fa-circle"></i>
            <i class="fa-solid fa-circle"></i>
            <i class="fa-regular fa-circle"></i>
            <i class="fa-regular fa-circle"></i>
            </div>
            <% when 8 %>
             <div class="d-flex">
            <i class="fa-solid fa-circle"></i>
            <i class="fa-solid fa-circle"></i>
            <i class="fa-solid fa-circle"></i>
            <i class="fa-solid fa-circle"></i>
            <i class="fa-regular fa-circle"></i>
            </div>
            <% when 9 %>
             <div class="d-flex">
            <i class="fa-solid fa-circle"></i>
            <i class="fa-solid fa-circle"></i>
            <i class="fa-solid fa-circle"></i>
            <i class="fa-solid fa-circle"></i>
            <i class="fa-solid fa-circle"></i>
            </div>

            <% end %>

        </div>
</div>










<style>
@import url('https://fonts.googleapis.com/css2?family=Changa+One&display=swap');
@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300&display=swap');

@keyframes reveal-left-to-right {
  from {
    opacity: 0;

    transform: translateX(110%);
  }
  to {
    opacity: 1;
    transform: translateX(0px);
  }
}

@keyframes reveal-right-to-left {
  from {
    opacity: 0;
    transform: translateX(-110%);
  }
  to {
    opacity: 1;
    transform: translateX(0px);
  }
}
@keyframes counter-reveal {
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
}

@keyframes grow-line {
  from {

    opacity: 0;
    height: 0;
  }
  to {
    opacity: 1;
    height: 100%;
  }
}
.counter {
  position: relative;
  top: -290px;
  color: #ed6d76;
  opacity: 0;
  animation: counter-reveal ease-out 1s forwards;
  animation-delay: 2.5s;
}

.container-new {
  position: relative;
  top: -600px;
  right: 138px;
  background-color: transparent;
  /* min-height: 100vh; */
  display: flex;
  justify-content: center;
  align-items: center;
}

#container-show {
  position: absolute;
}

.parent-div {

  background-color: transparent;
  height: 200px;
  width: 50%;
  display: flex;
  justify-content: space-between;
}

 /* .line-break-container {

  display: flex;
  align-items: center;
}

 #line-break {
  width: 2px;

  background-color: #ff6472;
  z-index: 3;
  animation: grow-line linear 1s forwards;
  animation-delay: 1s;
}  */

.img-container {
  height: 100%;
  overflow: hidden;
  flex: 1 0 auto;
  display: flex;
  justify-content: center;
  align-items: center;
}

#img1, #img2 {
  color: white;
  background-color: rgba(249, 156, 166, 0.954);
  font-size: 1.5rem;
  overflow: hidden;
  width: 300px;
  height: 70px;
  font-family: 'Poppins', sans-serif;
  display: flex;
  justify-content: center;
  align-items: center;
  border-radius: 5px;
}

#img1 {
  transform: translateX(110%);
  animation: reveal-left-to-right ease-out 1s forwards;
  animation-delay: 2.5s;
}

#img2 {
  transform: translateX(-110%);
  animation: reveal-right-to-left ease-out 1s forwards;
  animation-delay: 2.5s;
}


</style>

<script>
// document.addEventListener("DOMContentLoaded", () => {
//   setTimeout(() => {
//     const img1 = document.querySelector("#img1");
//     const img2 = document.querySelector("#img2");
//     img1.className += "apply-animation";
//     img2.className += "apply-animation";
//   }, 1300);
// });
</script>

app/views/receiptors/create.html.erb
<h1>Receiptors#create</h1>
<p>Find me in app/views/receiptors/create.html.erb</p>

app/views/settings/index.html.erb
<%= render "shared/navbarblack" %>

<div class="login-page">
  <div class="login-container">
    <div class="signup-form row justify-content-center align-items-center">
      <div class="col-6 col-sm-4">
        <h2>User Settings</h2>
        <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name), data: { turbo: :false }) do |f| %>
          <%= f.error_notification %>
              <%= f.input :email, required: true, autofocus: true, input_html: { autocomplete: "email" }%>
              <%= f.input :password, required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length), input_html: { autocomplete: "new-password" } %>
              <%= f.input :password_confirmation, required: true, input_html: { autocomplete: "new-password" } %>
              <%= f.button :submit, "Sign up", class: "btn btn-default btn-light" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-lewagon ">
  <div class="container-fluid">

  <div  class="d-flex justify-content-start" style="align-items: center">
      <div>
        <%= link_to root_path, class: "navbar-brand" do %>
          <%= image_tag "https://res.cloudinary.com/dmn9i4cwm/image/upload/v1680111412/apple-icon-57x57_aqpov4.png"%>
          <% end %>
      </div>

      <div class="navbar-brand-name">
      DINDER
      </div>
  </div>


    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
        <li class="nav-item dates">
             <%= link_to "My Dates", "/choices", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= cl_image_tag current_user.photo.key, height: 57, width: 57, crop: "fill", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Plan new Date", choices_path, data: {turbo_method: :post }, class: "dropdown-item" %>
              <%= link_to "Settings", "/users/edit", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>

           <li class="nav-item">

            <div class="btn">
              <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            </div>
          </li>
          <li class="nav-item">
            <div class="btn btn-sign-up">
              <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbarblack.html.erb
<div class="navbar navbar-expand-sm navbar-lewagonb ">
  <div class="container-fluid">
  <div  class="d-flex justify-content-start" style="align-items: center">
      <div>
        <%= link_to root_path, class: "navbar-brandb" do %>
          <%= image_tag "https://res.cloudinary.com/dmn9i4cwm/image/upload/v1680111412/apple-icon-57x57_aqpov4.png"%>
          <% end %>
      </div>

      <div class="navbar-brand-nameb">
      DINDER
      </div>
  </div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
        <li class="nav-itemb">
             <%= link_to "My Dates", "/choices", class: "nav-linkb" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://res.cloudinary.com/dmn9i4cwm/image/upload/v1679080308/production/y9ekpkdyx64i42pz4fsxroif2v1a.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Plan new Date", choices_path, data: {turbo_method: :post }, class: "dropdown-item" %>
              <%= link_to "Settings", "/settings/#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
      <% else %>
          <li class="nav-item">

            <div class="btn btn-secondary d-none">

              <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            </div>
          </li>
          <li class="nav-item">
            <div class="btn btn-sign-up">
              <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>